### ISSUE TITLE
Support for Stack and Containers

### ISSUE THREAD

**Issue by boxOfAces** [jushutch/swiping_card_deck#19]
getCardDeck to be made generic (extended to Stack and Containers)

**Comment by jushutch** [comment]
Hi @boxOfAces, thank you for opening this issue, I apologize for the delayed response! This is a great suggestion and something that was discussed more in issue #18. As of now, I'm planning on releasing a generic version of the SwipingCardDeck in a later release, so keep an eye out. In the meantime, feel free to contribute to the discussion in the issue I mentioned earlier. I'll close this one as a duplicate just so we can keep everything in one place. Thank you again!
