### ISSUE TITLE
Enable a control over the speed of the animation

### ISSUE THREAD

**Issue by fds101** [jushutch/swiping_card_deck#21]
When swiping the animation is really fast and sometimes not nearly noticeable. It would be a great enhancement to be able to control the speed at which the animation takes the card from the screen.

**Comment by jushutch** [comment]
Hello @fds101, thank you for opening this issue, I think this is a great idea! It should be pretty easy to expose the animation duration as an optional parameter, I'd be happy to do this soon and publish it in the next minor release.

**Comment by jushutch** [comment]
@fds101 I just published v1.1.0 with this feature, you can look at Pull Request #22 to read about the change and how to use the new `swipeAnimationDuration` parameter. Let me know if you have any questions and thank you again for opening this issue! 🎉
