### ISSUE TITLE
Excellent widget, but how to refresh deck?

### ISSUE THREAD

**Issue by josephmaklc** [jushutch/swiping_card_deck#28]
This is an excellent widget, swipe left and right to go to the next card... but at the bottom, there seems to be no way to reset. Is there an option to swipe left (or right) to put in bottom of deck again so it can be in a endless loop? (Great for something like children's flash cards app)

**Comment by jushutch** [comment]
Hi @josephmaklc, thank you for opening this issue and apologies for the delayed response! This functionality is possible using the prerelease v2.0.0-dev.0, which adds support for adding cards to a deck on left or right swipes. For an example, check out this comment that explains how to add a new card to the back of the deck: https://github.com/jushutch/swiping_card_deck/issues/23#issuecomment-1037829607. You'll want to do something similar, except you'll be adding the card that was just swiped to the back of the deck, which would look something like this:
```dart
onLeftSwipe: (Card card, List<Card> cardDeck, int cardsSwiped) {
  cardDeck.insert(0, card);
}
```
Check out the linked comment to learn more about the prerelease and how to use it. Let me know if I answered your question or if there's anything else I can do to help, thank you!
