### ISSUE TITLE
SwipingDeck controller

### ISSUE THREAD

**Issue by nanox77** [jushutch/swiping_card_deck#29]
Hi, I'm wondering if there is a chance of add a **swiping deck controller** to manage `SwipingDeck` from outside. I mean, I have a stack of cards, so far so good but I can't swipe current card using a button. Thank you!

**Comment by jushutch** [comment]
Hi @nanox77, thank you for opening this issue and apologies for the delayed response! Have you tried using the exposed `SwipingCardDeck.swipeLeft()` and `SwipingCardDeck.swipeRight()` functions with buttons? Here's an example:
```dart
IconButton(
  icon: const Icon(Icons.clear),
  iconSize: 30,
  color: Colors.red,
  onPressed: deck.swipeLeft(),
)
```
Calling these functions should allow you to swipe cards right or left with buttons. Let me know if that works for you or if you need something more complex for your use case, I'm happy to help!

**Comment by Teomayo** [comment]
I used these functions with buttons and can successfully swipe right / left. If you give an example chunk of code I can possibly help @nanox77
