### ISSUE TITLE
Create GitHub Actions workflow to run tests for pull requests

### ISSUE THREAD

**Issue by jushutch** [jushutch/swiping_card_deck#3]
Create a simple GitHub Action workflow to run the package test suite for every open pull request. A correct workflow should run `flutter test` for every update on a pull request and block it from being merged if tests fail. The naming of the workflow should be descriptive and concise.

**Comment by inovaprog** [comment]
Hi, @jushutch, 
I would like to work on this issue.

**Comment by jushutch** [comment]
Hi @inovaprog, I'll assign you now, good luck!

**Comment by inovaprog** [comment]
Thanks, @jushutch . But I think I have to wait for issue #2 to be resolved first.

**Comment by jushutch** [comment]
> Thanks, @jushutch . But I think I have to wait for issue #2 to be resolved first.

You're right because `flutter test` will fail without any tests. I'll create a single test to prevent that and add a comment here when I'm done with that. In the meantime you should still be able to work on the workflow, it just won't run successfully.

**Comment by inovaprog** [comment]
Thank you @jushutch . I will work in it now.
